import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import { defineConfig, globalIgnores } from 'eslint/config';
import tseslint from 'typescript-eslint';

export default defineConfig(
  globalIgnores([
    '**/node_modules/',
    '**/.next/',
    '**/dist/',
    '**/coverage/',
    '**/.turbo/',
    'playwright-report/',
    'test-results/',
    // Generated by Next.js on every dev, build and typegen run; not source.
    '**/next-env.d.ts',
  ]),
  js.configs.recommended,
  tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      'no-restricted-properties': [
        'error',
        {
          object: 'process',
          property: 'env',
          message: 'Read environment variables through @tas/env (packages/env) only.',
        },
      ],
    },
  },
  {
    files: ['packages/env/**'],
    rules: {
      'no-restricted-properties': 'off',
    },
  },
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Repo maintenance scripts run under Node directly, not through the bundler. `getComputedStyle`
    // is here because a verification script passes callbacks to Playwright's `page.evaluate`, which
    // runs them in the browser; ESLint reads them as ordinary Node code.
    files: ['scripts/**/*.{js,mjs,cjs}'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        getComputedStyle: 'readonly',
      },
    },
  },
  prettier,
);
