import {
  CREATIVE_DIMENSIONS,
  CREATIVE_NAME_SEPARATOR,
  CREATIVE_VERSIONS,
  STANDALONE_CONCEPT_SLUG,
  creativeDimensionEntry,
  creativeTypeLabel,
  creativeVersionLabel,
  dimensionsFor,
  normalizeCreativeDimensions,
  priorityTone,
  prioritySlaLabel,
  creativePriorityLabel,
  type CreativeDimensionEntry,
} from '@tas/domain/creatives';
import type { InspoLinkKind } from '@tas/domain/angles';
import { inheritedFromAngle } from '@tas/domain/concepts';
import {
  CLIENT_STATUS,
  chipTone,
  editorStageLabel,
  editorStageOf,
  editorStageTone,
  internalStatusFor,
  internalTransitionsFor,
  type ChipTone,
  type CreativeTrack,
  type EditorStageKey,
  type InternalStatusKey,
} from '@tas/domain/state';
import type {
  BriefListRow,
  ClientAssetFolderListRow,
  CreativeModuleListRow,
  CreativeReportListRow,
  CreativeSheetItemListRow,
} from '@tas/db';
import { creativePerformances, type CreativePerformance } from '@tas/db/schema';

import { differenceCpaView, formatCurrency } from '@/app/app/creative-reporting/fields';
import {
  SELECTION_PARAM as SHEET_SELECTION_PARAM,
  internalStatusView as sheetInternalStatusView,
  statusView as sheetStatusView,
  type SheetStatusView,
} from '@/app/app/creative-sheet/fields';
import { creativeSheetPath } from '@/lib/routes';

import type { BriefFieldName, BriefQaCheck } from './actions';

/**
 * How the Creative Briefs route presents what it stores (PRD §5.10). One module, so the list, the
 * detail page and the `/design-system` preview cannot drift: the column order, the labels, the em
 * dash, the QA checklist's three labels and the status-to-chip mapping are each stated exactly once.
 *
 * Nothing here invents a vocabulary. Type, Priority, Version and the delivery ratios come from
 * `@tas/domain/creatives`, every status label and chip tone from `@tas/domain/state`, and the
 * inspiration providers from `@tas/domain/angles`. No component writes `'Motion Image'`,
 * `'Static High'`, `'9:16'` or `'approved'`.
 *
 * `@tas/db` is imported for its TYPES only: the workspace and the detail form are client components,
 * and a runtime import of that package would drag the database driver into the browser bundle. A
 * type-only import is erased. Everything a client needs is handed down from `page.tsx` as plain data.
 * The one RUNTIME import from the database package is `creativePerformances` out of `@tas/db/schema`
 * — the pure Drizzle barrel `creative-sheet/fields.ts` makes the same import of — so the Performance
 * select renders the storage vocabulary itself rather than a copy of it.
 */
export type { BriefFieldName, BriefQaCheck };
export { STANDALONE_CONCEPT_SLUG };

/** The dash an empty field shows, so a blank cell is never just a gap. */
export const EM_DASH = '—';

/** What the demo footer says instead of offering a save. */
export const DEMO_FOOTER_NOTICE = 'Demo mode — changes are not saved';

/**
 * The quiet line under the generated name. A creative name is built by the §7 formula from the
 * fields below it (CLAUDE.md non-negotiable 4), so the page has to say so rather than leave a
 * reader hunting for an input that was deliberately never built.
 */
export const NAME_GENERATED_NOTE =
  'Generated by the formula when the creative was created; a concept rename keeps it in step. This name is never typed.';

/** The same line for a `manual` name: imported from Airtable or typed by hand, and left alone. */
export const NAME_MANUAL_NOTE =
  'Imported or typed by hand, stored as it is. Nothing rewrites this name.';

/** The copy button's two states. It confirms in place rather than opening a toast (criterion 4). */
export const COPY_LABEL = 'Copy';
export const COPIED_LABEL = 'Copied';

/** The one sentence the left column shows in place of a concept card (PRD §8). */
export const STANDALONE_NOTE =
  'No parent concept. A static can be briefed on its own, so this one carries its own batch and product.';

/** The URL parameter the search lives in, the same `?q=` every other list page uses. */
export const SEARCH_PARAM = 'q';

/*
 * The grid's columns are NOT a list in this file any more (AI-64a). `BRIEF_COLUMNS` was a six-string
 * tuple here, which made the label, the order and which fields exist at all code facts — no relabel,
 * no hiding, and the fields Gratsi's base carries simply absent. The page reads
 * `resolveColumns(db, brandId, 'creative_briefs')` through `loadBriefColumns()` and draws each
 * resolved column through `BRIEF_RENDERERS` in `briefs-workspace.tsx`.
 */

/** The name of one row linked by a foreign key, or `null` when the link is absent or no longer live. */
export function linkedName(id: string | null, names: ReadonlyMap<string, string>): string | null {
  return id === null ? null : (names.get(id) ?? null);
}

/**
 * The PERSONA a brief inherits (AI-54, PRD §5.10: "Concept (link) → auto-fills Batch, Angle,
 * Persona, Product").
 *
 * A brief has no persona column, and never should: the persona hangs off the ANGLE, so the chain is
 * brief → angle → personas, and the one place that chain is resolved is
 * `inheritedFromAngle` in `@tas/domain/concepts` — the same function the concept detail reads its
 * five inherited fields from. This is only the adapter: it turns the angle row the facts list is
 * already naming into that function's structural input and returns the `personaName` entry.
 *
 * EVERY persona of the angle, comma-joined, not the first of several — `angle_personas` is a
 * junction, and `inheritedFromAngle` already joins the list when it is given one. That matters here
 * because the fact sits beside Angle and Product, which carry the opposite, honestly-documented
 * caveat (the concept's FIRST angle and that angle's FIRST product).
 */
export interface BriefPersonaAngle {
  readonly personaIds: readonly string[];
  /** The angle's first persona, already resolved — the fallback when no id maps to a name. */
  readonly personaName: string | null;
}

export function briefPersonaName(
  angle: BriefPersonaAngle | null,
  personaNames: ReadonlyMap<string, string>,
): string | null {
  if (angle === null) {
    return null;
  }
  const [persona] = inheritedFromAngle({
    description: null,
    painPoints: null,
    usp: null,
    personaName: angle.personaName,
    productName: null,
    personaNames: angle.personaIds
      .map((id) => personaNames.get(id) ?? '')
      .filter((name) => name !== ''),
  }).filter((field) => field.key === 'personaName');
  return persona?.value ?? null;
}

/**
 * The editor-board stage this brief sits at, with its label and tone — `null` once it has left the
 * board. The stage is a VIEW of `internal_status` and never a second column, so `EDITOR_STAGES` in
 * `@tas/domain/state` owns the three words and their tones and the Kanban stripe, the detail chip
 * and the grid's primary cell all read them from here rather than each choosing a colour.
 */
export interface BriefStageView {
  readonly key: EditorStageKey;
  readonly label: string;
  readonly tone: ChipTone;
}

export function briefStageView(internalStatus: string): BriefStageView | null {
  const key = editorStageOf(internalStatus);
  return key === null ? null : { key, label: editorStageLabel(key), tone: editorStageTone(key) };
}

/** One status, ready to render: the stored key, its label and the chip tone it carries. */
export interface BriefStatusView {
  readonly key: InternalStatusKey;
  readonly label: string;
  readonly tone: ChipTone;
}

/**
 * The view of one stored internal status on its own track. Total on purpose: a key this build's
 * track does not list renders its own value in the muted tone rather than an empty cell.
 */
export function internalStatusView(track: CreativeTrack, key: InternalStatusKey): BriefStatusView {
  const entry = internalStatusFor(track).find((step) => step.key === key);
  return entry === undefined
    ? { key, label: key, tone: 'mute' }
    : { key: entry.key, label: entry.label, tone: chipTone(entry.label) };
}

/** The client-facing status as its chip — the board sidebar's Client Status line (P2B-3). */
export interface BriefClientStatusView {
  readonly key: string;
  readonly label: string;
  readonly tone: ChipTone;
}

/**
 * The view of one stored client status. Total the same way `internalStatusView` is: an unknown key
 * renders its own value muted rather than an empty cell.
 */
export function clientStatusView(key: string): BriefClientStatusView {
  const entry = CLIENT_STATUS.find((step) => step.key === key);
  return entry === undefined
    ? { key, label: key, tone: 'mute' }
    : { key: entry.key, label: entry.label, tone: chipTone(entry.label) };
}

/** A priority as its chip: the label, the tone the clock earns it, and the SLA it promises. */
export interface BriefPriorityView {
  readonly label: string;
  readonly tone: ChipTone;
  /** `12h`, or `null` for a brief nobody has prioritised yet. */
  readonly sla: string | null;
}

export function priorityView(priority: string | null): BriefPriorityView | null {
  if (priority === null) {
    return null;
  }
  return {
    label: creativePriorityLabel(priority),
    tone: priorityTone(priority),
    sla: prioritySlaLabel(priority),
  };
}

/** One Performance grade, ready to render: the stored value, its label and the chip tone it carries. */
export interface BriefPerformanceView {
  readonly key: string;
  readonly label: string;
  readonly tone: ChipTone;
}

/**
 * The tone of each Performance grade, keyed on the schema's own vocabulary so a fourth grade cannot
 * be added to `creativePerformances` without this map being told its tone. A local total map
 * rather than `chipTone(label)`, for the reason `creative-sheet/fields.ts` gives for its own
 * `WINNING_TONE`: the domain's label map has no rule for these words and would read all three as
 * `mute`. A winner is `ok`, a loser is `bad`, and the one worth iterating is `info` — the "look at
 * this" tone, neither a verdict nor a warning.
 */
const PERFORMANCE_TONE: Record<CreativePerformance, ChipTone> = {
  Winning: 'ok',
  'High Potential to Iterate': 'info',
  Losing: 'bad',
};

/** The Performance dropdown's options, in schema order, each already carrying its tone. */
export const PERFORMANCE_OPTIONS: readonly BriefPerformanceView[] = creativePerformances.map(
  (key) => ({ key, label: key, tone: PERFORMANCE_TONE[key] }),
);

/** The label of the dropdown's "no grade" option, which the action stores as NULL. */
export const NOT_GRADED_LABEL = 'Not graded yet';

/**
 * The view of one stored Performance grade, or null for a brief that has not run (PRD §5.10: null
 * until it has). Total the same way `internalStatusView` is: a value this build does not list
 * renders its own text in the muted tone rather than an empty cell.
 */
export function performanceView(performance: string | null): BriefPerformanceView | null {
  if (performance === null) {
    return null;
  }
  return (
    PERFORMANCE_OPTIONS.find((option) => option.key === performance) ?? {
      key: performance,
      label: performance,
      tone: 'mute',
    }
  );
}

/**
 * A stored grade the dropdown does not list, as its muted view — or null when the brief is ungraded
 * or carries one of the three. `creative_briefs.performance` is plain `text` with no CHECK, and the
 * Airtable importer writes the Gratsi choice unmapped (`Winning (ROAS/CPA Goal)` and its siblings),
 * so a live row can hold a value `creativePerformances` does not name. The detail page offers it as
 * one extra item so the trigger is never blank, and withholds the hidden input while it is still
 * the choice, so the action's "absent means leave it" branch keeps the grade rather than refusing
 * the whole save over a field nobody touched.
 */
export function unlistedPerformance(performance: string | null): BriefPerformanceView | null {
  if (performance === null || PERFORMANCE_OPTIONS.some((option) => option.key === performance)) {
    return null;
  }
  return performanceView(performance);
}

/**
 * The raw fields the update action needs to rebuild FormData on a Kanban drag. Every field that
 * `fieldsOf()` in `actions.ts` reads is here, with ONE deliberate exception: `performance`. The
 * board never offers a grade, so a drag must not blank one — the snapshot omits it and the rebuilt
 * FormData carries no `performance` key at all, which is the `optional('performance')` branch of
 * `fieldsOf()`: absent means the stored grade is left alone. Kept as plain strings (the FormData
 * shape) so the client never parses or validates — the action does that.
 */
export interface BriefFormSnapshot {
  readonly conceptId: string;
  readonly funnel: string;
  readonly type: string;
  readonly version: string;
  readonly batch: string;
  readonly product: string;
  readonly priority: string;
  readonly assignee: string;
  /** `YYYY-MM-DD` or empty, as the date input posts it. */
  readonly dueDate: string;
  readonly briefToDesign: string;
  readonly scriptContent: string;
  readonly elementsTested: string;
  readonly adContent: string;
  readonly inspiration: string;
  readonly offer: string;
  readonly language: string;
  readonly spellingFeedback2: string;
  readonly angleId: string;
  readonly productId: string;
  readonly inspoLinks: readonly string[];
  readonly dimensions: readonly string[];
  readonly internalStatus: string;
  readonly clientStatus: string;
}

/**
 * One brief as the list renders it: everything the table shows, and nothing else. Built on the
 * server so the client component never imports `@tas/db` and never resolves a status itself.
 */
export interface BriefItem {
  readonly id: string;
  readonly name: string;
  /** The parent concept's generated name, or `null` — the ordinary PRD §8 standalone case. */
  readonly conceptName: string | null;
  readonly type: string;
  readonly typeLabel: string;
  readonly priority: BriefPriorityView | null;
  readonly assignee: string | null;
  readonly status: BriefStatusView;
  /** The client-facing track, for the board sidebar's quick read (P2B-3). */
  readonly clientStatus: BriefClientStatusView;
  /** The Performance grade as its chip, or null for a brief that has not run. */
  readonly performance: BriefPerformanceView | null;
  /** The editor-board stage, which colours the grid's primary cell; null once off the board. */
  readonly stage: BriefStageView | null;
  /**
   * The stored row itself, so a resolved column can be DRAWN rather than dropped. Most of the
   * thirty-six columns `creative_briefs` resolves to are plain stored fields with no view to
   * precompute, and re-listing each one here would be a second copy of the schema for the next
   * migration to outdate. The same shape Personas and Copy Types take (`{ persona }`,
   * `{ copyType }`); `@tas/db` is a TYPE-only import here, so no driver reaches the browser.
   */
  readonly row: BriefListRow;
  /** The names behind the brief's own foreign keys, resolved on the server; null when absent. */
  readonly angleName: string | null;
  readonly productName: string | null;
  readonly collectionName: string | null;
  readonly campaignOfferName: string | null;
  readonly assetName: string | null;
  /** Funnel and Source as the sidebar shows them; Source is stored display-ready ("TAS"/"Client"). */
  readonly funnelLabel: string;
  readonly sourceLabel: string;
  /** `briefPath(id)` — a real route segment, because the detail is a page and not a panel. */
  readonly href: string;
  /** Raw Kanban-groupable field values, keyed by column name. */
  readonly kanbanFields: Record<string, string>;
  /** First image URL from designFile or inspirationImage, for Gallery view. */
  readonly galleryImageUrl: string | null;
  /** All raw fields the update action needs, so Kanban drag can build FormData without re-fetching. */
  readonly formSnapshot: BriefFormSnapshot;
  /** How many rows of each counterpart table point at this brief — the panel's one-line read. */
  readonly linkCounts: BriefLinkCounts;
  /**
   * The Meta Copywriting rows whose `creative_brief_id` is this brief (GRATSI-MATCH 2026-10-04):
   * the reverse side of the copy table's `Creative` link, as generated Copy # titles, for the
   * read-only `Meta Copywriting` grid column. Indexed once on the server from the copy loader.
   */
  readonly metaCopy: readonly {
    readonly id: string;
    readonly label: string;
    readonly href?: string;
  }[];
  /**
   * Airtable's `Concepts (from Angles)` lookup, computed on the server by
   * `briefConceptsFromAngles` over the concepts paired with the brief's angle. Virtual — nothing
   * stores it — so the item carries the finished string the cell prints.
   */
  readonly conceptsFromAngles: string | null;
}

// ── Two-way links (module parity, phase 2) ──────────────────────────────────────────────────────

/**
 * The four tables that point AT a brief, each read back the other way here so the brief shows what
 * cites it. The links are one-directional in the schema — `creative_sheet_items.brief_id`,
 * `creative_module_designs`, `brief_asset_folders`, `creative_reporting.brief_id` — and the brief
 * never stores the inverse: these are computed from the counterpart rows on the server, by the
 * functions below, and handed down as plain data.
 */
export type BriefLinkKind = 'sheetItems' | 'modules' | 'folders' | 'reports';

/** One chip on a linked record: a sheet status, a CPA difference. */
export interface BriefLinkChip {
  readonly label: string;
  readonly tone: ChipTone;
}

/** One row of another table that points at this brief, as the rail's card renders it. */
export interface BriefLinkedRecord {
  readonly id: string;
  readonly label: string;
  /** True when the label is generated system output (a computed name), so it renders in `font-mono`. */
  readonly mono: boolean;
  /** The counterpart page, opened on this row's panel; `null` when the row has no page of its own. */
  readonly href: string | null;
  /** A quiet second line under the label, e.g. a report's CPA against its target. */
  readonly detail: string | null;
  readonly chips: readonly BriefLinkChip[];
}

export type BriefLinkedRecords = Readonly<Record<BriefLinkKind, readonly BriefLinkedRecord[]>>;
export type BriefLinkCounts = Readonly<Record<BriefLinkKind, number>>;

/** The counterpart rows, as each module's `load…` function returns them (fixtures or database). */
export interface BriefLinkSources {
  readonly sheetItems: readonly CreativeSheetItemListRow[];
  readonly modules: readonly CreativeModuleListRow[];
  readonly folders: readonly ClientAssetFolderListRow[];
  readonly reports: readonly CreativeReportListRow[];
}

/** One rail section: its data-slot, heading, empty-state sentence and the noun the count line uses. */
export interface BriefLinkSection {
  readonly kind: BriefLinkKind;
  readonly slot: string;
  readonly heading: string;
  readonly empty: string;
  readonly noun: readonly [singular: string, plural: string];
}

/** The rail's four link sections, in the order they render and the count line reads. */
export const BRIEF_LINK_SECTIONS: readonly BriefLinkSection[] = [
  {
    kind: 'sheetItems',
    slot: 'brief-creative-sheet',
    heading: 'Creative Sheet',
    empty: 'No sheet row names this creative yet. One appears when the month’s sheet links it.',
    noun: ['sheet row', 'sheet rows'],
  },
  {
    kind: 'modules',
    slot: 'brief-creative-modules',
    heading: 'Creative Modules',
    empty: 'No module groups this creative yet. Link it from the module’s panel.',
    noun: ['module', 'modules'],
  },
  {
    kind: 'folders',
    slot: 'brief-client-assets',
    heading: 'Client Asset folders',
    empty: 'No client asset folder feeds this creative yet. Link it from the folder’s panel.',
    noun: ['asset folder', 'asset folders'],
  },
  {
    kind: 'reports',
    slot: 'brief-creative-reports',
    heading: 'Creative Reports',
    empty: 'No report has been filed for this creative yet.',
    noun: ['report', 'reports'],
  },
];

export const NO_BRIEF_LINKS: BriefLinkCounts = {
  sheetItems: 0,
  modules: 0,
  folders: 0,
  reports: 0,
};

/**
 * The Creative Sheet opened on one row, through the selection parameter it exports. It is the only
 * counterpart still linked: the Creative Modules, Client Assets and Creative Reporting workspaces
 * are removed from the app (2026-10-09), so their records render with `href: null`.
 */
function sheetItemHref(id: string): string {
  return `${creativeSheetPath}?${SHEET_SELECTION_PARAM}=${encodeURIComponent(id)}`;
}

/** A report's one-line read, both sides formatted by the reporting module's own currency rule. */
export function cpaVsTargetLabel(cpa: string | null, targetCpa: string | null): string {
  return `CPA ${formatCurrency(cpa)} vs target ${formatCurrency(targetCpa)}`;
}

/**
 * Every row of the four counterpart tables that points at `briefId`, in the order each source
 * returns them, each already carrying its href, its chips and its detail line. Statuses and the
 * CPA difference are read through the counterpart module's own view functions, so a sheet chip on
 * this page and on the Creative Sheet cannot disagree.
 */
export function briefLinkedRecords(briefId: string, sources: BriefLinkSources): BriefLinkedRecords {
  return {
    sheetItems: sources.sheetItems
      .filter((row) => row.briefId === briefId)
      .map((row) => ({
        id: row.id,
        label: row.name,
        mono: true,
        href: sheetItemHref(row.id),
        detail: null,
        chips: [sheetInternalStatusView(row.internalStatus), sheetStatusView(row.status)]
          .filter((view): view is SheetStatusView => view !== null)
          .map((view) => ({ label: view.label, tone: view.tone })),
      })),
    modules: sources.modules
      .filter((row) => row.briefIds.includes(briefId))
      .map((row) => ({
        id: row.id,
        label: row.moduleName,
        mono: false,
        href: null,
        detail: null,
        chips: [],
      })),
    folders: sources.folders
      .filter((row) => row.briefIds.includes(briefId))
      .map((row) => ({
        id: row.id,
        label: row.name,
        mono: false,
        href: null,
        detail: null,
        chips: [],
      })),
    reports: sources.reports
      .filter((row) => row.briefId === briefId)
      .map((row) => {
        const difference = differenceCpaView(row.differenceCpa);
        return {
          id: row.id,
          label: row.nameAngleOffer,
          mono: false,
          href: null,
          detail: cpaVsTargetLabel(row.cpa, row.targetCpa),
          chips: difference === null ? [] : [difference],
        };
      }),
  };
}

/**
 * `briefId -> counts`, every brief any counterpart row points at, in one pass per source — so the
 * list page costs four reads for N briefs rather than four per brief. A brief nobody cites is absent;
 * the caller reads `NO_BRIEF_LINKS` for it.
 */
export function indexBriefLinkCounts(
  sources: BriefLinkSources,
): ReadonlyMap<string, BriefLinkCounts> {
  const index = new Map<string, Record<BriefLinkKind, number>>();
  const bump = (briefId: string, kind: BriefLinkKind): void => {
    const counts = index.get(briefId) ?? { ...NO_BRIEF_LINKS };
    counts[kind] += 1;
    index.set(briefId, counts);
  };
  // Every sheet row is a brief since the single-source cutover: the link is never empty.
  for (const row of sources.sheetItems) {
    bump(row.briefId, 'sheetItems');
  }
  for (const row of sources.modules) {
    for (const briefId of row.briefIds) bump(briefId, 'modules');
  }
  for (const row of sources.folders) {
    for (const briefId of row.briefIds) bump(briefId, 'folders');
  }
  for (const row of sources.reports) {
    if (row.briefId !== null) bump(row.briefId, 'reports');
  }
  return index;
}

/** The panel's count line: `1 sheet row · 2 modules · 0 asset folders · 1 report`. Never "1 rows". */
export function linkCountLabel(counts: BriefLinkCounts): string {
  return BRIEF_LINK_SECTIONS.map((section) => {
    const count = counts[section.kind];
    return `${String(count)} ${count === 1 ? section.noun[0] : section.noun[1]}`;
  }).join(' · ');
}

/** How the header counts what is on screen. Singular at one, never "1 briefs". */
export function briefCountLabel(count: number): string {
  return `${String(count)} ${count === 1 ? 'brief' : 'briefs'}`;
}

/** The count line while the search is narrowing the list, so "6 briefs" never contradicts 1 row. */
export function filteredBriefCountLabel(visible: number, total: number): string {
  return `${String(Math.max(Math.floor(visible), 0))} of ${briefCountLabel(total)}`;
}

/**
 * The search reads everything the table shows: the generated name, the concept, the type label, the
 * priority, the assignee and the internal status LABEL — so "revisions" finds the row whose chip
 * says `Images Revisions` without this module ever writing that string, and "standalone" finds the
 * brief with no concept because that cell renders the slug. `query` arrives lowercased and trimmed.
 */
export function matchesQuery(item: BriefItem, query: string): boolean {
  if (query === '') {
    return true;
  }
  return [
    item.name,
    item.conceptName ?? STANDALONE_CONCEPT_SLUG,
    item.typeLabel,
    item.priority?.label ?? '',
    item.assignee ?? '',
    item.status.label,
  ].some((value) => value.toLowerCase().includes(query));
}

/**
 * The empty state's two sentences, which say different things and must never be collapsed into one.
 * A brand with nothing in it is offered the primary action; a search that matches nothing is
 * offered its way back, because "New brief" would answer a question nobody asked.
 */
export const NO_BRIEFS_NOTE =
  'No creative briefs yet. One brief is one creative asset, and its name writes itself.';

export const NO_MATCH_NOTE = 'No brief matches this search. Clear it to see every creative.';

/**
 * Why "New brief" is inert outside demo mode too: `createBriefAction` exists and is tested, but the
 * create FORM is not part of this ticket, so the button would have nothing to submit.
 */
export const NEW_BRIEF_SOON_HINT = 'The create form ships with the CSV upload ticket';

/** Why "Re-run AI check" is inert outside demo mode: there is no Server Action behind it yet. */
export const RERUN_SOON_HINT = 'The spelling check runs as a background job in a later ticket';

/** The three QA checkboxes of ticket criterion 10, in the order the checklist lists them. */
export const BRIEF_QA_CHECKS = ['qaVideoEditor', 'qaDesigner', 'qaStrategist'] as const;

/** Their labels, the table `actions.ts` could not export from a `'use server'` module. */
export const BRIEF_QA_LABELS: Record<BriefQaCheck, string> = {
  qaVideoEditor: 'Video Editor QA',
  qaDesigner: 'Graphic Designer QA',
  qaStrategist: 'Creative Strategist QA',
};

/** The detail page's headings, each stated once so the page and the E2E assertion agree. */
export const BRIEF_HEADINGS = {
  concept: 'Concept',
  batch: 'Batch',
  angle: 'Angle',
  persona: 'Persona',
  product: 'Product',
  performance: 'Performance',
  assignee: 'Assignee',
  dueDate: 'Due date',
  stage: 'Stage',
  scripts: 'Scripts',
  activity: 'Activity',
  type: 'Type',
  source: 'Source',
  funnel: 'Funnel',
  platform: 'Platform',
  designLinkUrl: 'Design Link URL',
  collection: 'Collection',
  asset: 'Assets',
  metaCopywriting: 'Copywriting',
  version: 'Version',
  priority: 'Priority',
  dimensions: 'Dimensions',
  briefToDesign: 'Brief to Design',
  scriptContent: 'Script or Ad Content',
  elementsTested: 'Elements we are Testing',
  adContent: 'Ad Content',
  inspiration: 'Inspiration',
  inspirationNotes: 'Inspiration Notes',
  offer: 'Offer',
  language: 'Language',
  spellingFeedback2: 'Spelling Feedback 2',
  designFile: 'Design File',
  qaChecklistDoc: 'QA Checklist Doc',
  inspirationImage: 'Inspiration Image',
  scriptAndBriefBreakdown: 'Script & Brief Breakdown',
  approval: 'Approval',
  qa: 'QA checklist',
  spelling: 'Spelling Feedback',
} as const;

/** The three prose sections of the centre column, in order, with what each one is for. */
export const BRIEF_PROSE_FIELDS = [
  {
    name: 'briefToDesign',
    label: BRIEF_HEADINGS.briefToDesign,
    hint: 'What the designer or editor builds, shot by shot.',
  },
  {
    name: 'scriptContent',
    label: BRIEF_HEADINGS.scriptContent,
    hint: 'The words on screen and the words spoken, in order.',
  },
  {
    name: 'elementsTested',
    label: BRIEF_HEADINGS.elementsTested,
    hint: 'The hypothesis this creative exists to settle.',
  },
  {
    name: 'adContent',
    label: BRIEF_HEADINGS.adContent,
    hint: 'The ad content prose for this creative.',
  },
  {
    name: 'inspiration',
    label: BRIEF_HEADINGS.inspirationNotes,
    hint: 'Inspiration notes for this creative.',
  },
] as const satisfies readonly { name: BriefFieldName; label: string; hint: string }[];

/** The empty state of the Inspiration section, so an empty array is never a blank panel. */
export const NO_INSPIRATION_NOTE = 'No inspiration saved on this creative yet.';

/** The empty state of the Spelling Feedback panel. */
export const NO_SPELLING_NOTE = 'The AI check has not run on this creative yet.';

/** The empty state of the Spelling Feedback 2 panel — the second pass, read-only like the first. */
export const NO_SPELLING_2_NOTE = 'No second spelling pass has been recorded on this creative yet.';

/** The short source name on an inspiration card. `inspirationLink` owns which provider a URL is. */
const INSPIRATION_SOURCE_LABELS: Record<InspoLinkKind, string> = {
  'meta-ad-library': 'Meta Ad Library',
  youtube: 'YouTube',
  tiktok: 'TikTok',
  instagram: 'Instagram',
  other: 'Link',
};

export function inspirationSourceLabel(kind: InspoLinkKind): string {
  return INSPIRATION_SOURCE_LABELS[kind];
}

/** The version dropdown's options, V1…V6, labelled by the domain so nothing retypes the `V`. */
export const VERSION_OPTIONS: readonly { key: string; label: string }[] = CREATIVE_VERSIONS.map(
  (version) => ({ key: String(version), label: creativeVersionLabel(version) }),
);

/**
 * The Dimensions multi-select's options, in `CREATIVE_DIMENSIONS` order (PRD §8). Rendered as a
 * dropdown checklist so the detail page can CHANGE which ratios a brief ships in, where before the
 * grid was read-only and the hidden inputs were pinned to the stored array. A direct re-export of
 * the domain tuple so no component chooses a label, a pixel size or an order of its own.
 */
export const BRIEF_DIMENSION_OPTIONS: ReadonlyArray<(typeof CREATIVE_DIMENSIONS)[number]> =
  CREATIVE_DIMENSIONS;

/**
 * The ratios a brief delivers in: its own stored array when it has one, and PRD §8's defaults for
 * its type when it does not. A row written before the defaults existed therefore still shows a grid
 * rather than an empty box, and an edited row shows what it was edited to.
 */
export function briefDimensions(
  stored: readonly string[],
  type: string,
): readonly CreativeDimensionEntry[] {
  return briefDimensionKeys(stored, type)
    .map((key) => creativeDimensionEntry(key))
    .filter((entry): entry is CreativeDimensionEntry => entry !== undefined);
}

/**
 * The values the Dimensions picker is seeded with: the stored array NORMALISED — an imported
 * Airtable placement name read as its ratio, a name this build cannot place kept as it is — or
 * the §8 defaults for the type when the row carries nothing. The 2026-10-10 smoke test found the
 * picker looking the stored names up raw, so an imported brief read as empty: no checkmarks, and
 * its first tick would have saved one ratio over three.
 */
export function briefDimensionKeys(stored: readonly string[], type: string): string[] {
  return stored.length === 0 ? [...dimensionsFor(type)] : normalizeCreativeDimensions(stored);
}

/** What the picker says around its save-on-tick: it writes on every tick, with no Save button. */
export const BRIEF_DIMENSIONS_SAVE_LABELS = {
  hint: 'Saves on each tick.',
  pending: 'Saving…',
  saved: 'Saved',
  none: 'Choose dimensions',
} as const;

/**
 * The next step on this brief's own internal ladder, or `null` at the end of it.
 *
 * Read from the state machine's transition table, never from a list written here. `on_hold` is
 * skipped on purpose: it is the non-linear branch the handoff renders as a side badge, so it is not
 * what "advance" means, and the button offers the linear next step the stepper can draw.
 */
export function nextInternalStatus(
  track: CreativeTrack,
  current: InternalStatusKey,
): BriefStatusView | null {
  const allowed = internalTransitionsFor(track)[current] ?? [];
  const next = internalStatusFor(track).find((entry) => allowed.includes(entry.key));
  return next === undefined ? null : internalStatusView(track, next.key);
}

/** What the advance button says, so the label and the step it moves to cannot disagree. */
export function advanceLabel(next: BriefStatusView): string {
  return `Advance to ${next.label}`;
}

/**
 * The optional PRD §7 product suffix of a generated name, or `null` when it carries none.
 *
 * There is no `product` column: §7's suffix lives only inside the name, because it disambiguates a
 * creative whose concept does not already name the product — in practice the standalone static.
 * A save re-computes the whole name from its parts, so the suffix has to be readable back out of
 * the one place it is stored, or the next save would silently drop it.
 *
 * The version segment is the anchor: everything after the LAST `V<number>` segment is the suffix.
 * Anchoring on the version rather than on a hyphen count is what keeps `POV: X vs Y` and every
 * other hyphenated concept name intact.
 */
export function productSuffixOf(name: string, version: number): string | null {
  const segments = name.split(CREATIVE_NAME_SEPARATOR);
  const marker = creativeVersionLabel(version);
  const at = segments.lastIndexOf(marker);
  if (at === -1 || at === segments.length - 1) {
    return null;
  }
  const suffix = segments.slice(at + 1).join(CREATIVE_NAME_SEPARATOR);
  return suffix.trim() === '' ? null : suffix;
}

/** The type's human label, re-exported so a component never reaches past this module. */
export { creativeTypeLabel };

/** A due date as `<input type="date">` wants it: `YYYY-MM-DD` in UTC, or empty when unset. */
export function dueDateInputValue(value: Date | string | null | undefined): string {
  if (value === null || value === undefined) return '';
  const date = typeof value === 'string' ? new Date(value) : value;
  return Number.isNaN(date.getTime()) ? '' : date.toISOString().slice(0, 10);
}
